name: 'Tags Test'

on:
  push:
    branches:
      - master
    tags:
      - '*-stg-*'

jobs:
  tags-test:
    name: 'Tags processing'
    runs-on: ubuntu-latest
    steps:
      - run : echo ${{ github }}
