name: 'Tags Test'

on:
  push:
    branches:
      - main
    tags:
      - '*-[a-z]+?\.[0-9]+$'

jobs:
  tags-test:
    name: 'Tags processing'
    runs-on: ubuntu-latest
    steps:
      - run : echo ${{ github.ref }}
