name: 'Tags Test'

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-z].[0-9]+'

jobs:
  tags-test:
    name: 'Tags processing'
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo ${{ toJson(github) }} \
      - run: echo Done
